version: '3.7'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=example
    - MONGO_INITDB_DATABASE=mongo
  
  mongo-export:
    image: percona/mongodb_exporter:0.40
    command: "--collect-all"
    ports:
    - 9216:9216
    environment:
    - MONGODB_URI=mongodb://root:example@mongodb:27017
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
  
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    labels:
      logging: "promtail"
      loggin_jobname: "grafana-logs"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
