global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"
  - "host-and-hardware.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'mongo-export-1'
    static_configs:
      - targets: ['mongo-export:9216']
  
  - job_name: 'mongo-export-2'
    static_configs:
      - targets: ['mongos-exporter:8880']
